version: "1.0"
stages:
  - "clone"
  - "build"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "apexinternal/bingo-cat"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "apexinternal/bingo-cat"
    working_directory: "${{clone}}"
    tags:
      - "${{CF_BRANCH_TAG_NORMALIZED}}"
      - "latest"
    dockerfile: "Dockerfile"
    stage: "build"